### ISSUE TITLE
id generation issues

### ISSUE THREAD

**Issue by MichaelFedora** [MalekaiProject/crowfallData#15]
see: `Dig In!`, which generates an id of `dig_in!`, which does not play nice.

We need to replace *all* non-alpha-numeric characters with either nothing or dashes or underscores, and then trim those from the ends IMO.

**Comment by TheScree** [comment]
This is solved, only alpha-numeric characters get passed through during id generation. Any special characters are removed (no spaces injected in their place, just deleted via regex /w shortcut.
