### ISSUE TITLE
Proposition to add "Tags" to things

### ISSUE THREAD

**Issue by MichaelFedora** [MalekaiProject/crowfallData#23]
This is for better looking-ups. I.e.

Class tags: `ranged`, `melee`, `mixed`, `support`, `dps`, `specialist`, `stealth` (targeting-type & role, respectively)
Race tags: (idk but) `magical`, `human`, `mixed`, `purebred` (half-* could use both magical & human)
Discipline tags: `stealth`, `gathering`, `support`, etc
Power tags: `stealth`, `gathering`, `support`, `cc`, etc

**Comment by TheScree** [comment]
debuffs and buffs are also vital; trying to put together a list of those

**Comment by TheScree** [comment]
I'm generating rudimentary tags right now. I disagree we need tags for classes/races, but for powers and disciplines absolutely.

This is implemented in current version, however, it requires a well-defined lexicon to populate the tags properly. Creating a new issue on what items should be in this Lexicon.
